# Generated by Django 5.2.7 on 2025-10-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_alter_category_description_billorlaw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billorlaw',
            name='type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('LAW', 'Law')], max_length=10),
        ),
    ]
